// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateMaker(arg1) {
  return window['go']['main']['App']['CreateMaker'](arg1);
}

export function CreateModel(arg1) {
  return window['go']['main']['App']['CreateModel'](arg1);
}

export function CreateVehicle(arg1) {
  return window['go']['main']['App']['CreateVehicle'](arg1);
}

export function DeleteMaker(arg1) {
  return window['go']['main']['App']['DeleteMaker'](arg1);
}

export function DeleteModel(arg1) {
  return window['go']['main']['App']['DeleteModel'](arg1);
}

export function DeleteVehicle(arg1) {
  return window['go']['main']['App']['DeleteVehicle'](arg1);
}

export function GetAllMakers() {
  return window['go']['main']['App']['GetAllMakers']();
}

export function GetAllModels() {
  return window['go']['main']['App']['GetAllModels']();
}

export function GetAllVehicles() {
  return window['go']['main']['App']['GetAllVehicles']();
}

export function GetMaker(arg1) {
  return window['go']['main']['App']['GetMaker'](arg1);
}

export function GetModel(arg1) {
  return window['go']['main']['App']['GetModel'](arg1);
}

export function GetVehicle(arg1) {
  return window['go']['main']['App']['GetVehicle'](arg1);
}

export function UpdateMaker(arg1) {
  return window['go']['main']['App']['UpdateMaker'](arg1);
}

export function UpdateModel(arg1) {
  return window['go']['main']['App']['UpdateModel'](arg1);
}

export function UpdateVehicle(arg1) {
  return window['go']['main']['App']['UpdateVehicle'](arg1);
}
