// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateMaker(arg1:main.Maker):Promise<void>;

export function CreateModel(arg1:main.Model):Promise<void>;

export function CreateVehicle(arg1:main.Vehicle):Promise<void>;

export function DeleteMaker(arg1:string):Promise<void>;

export function DeleteModel(arg1:string):Promise<void>;

export function DeleteVehicle(arg1:string):Promise<void>;

export function GetAllMakers():Promise<Array<main.Maker>>;

export function GetAllModels():Promise<Array<main.Model>>;

export function GetAllVehicles():Promise<Array<main.Vehicle>>;

export function GetMaker(arg1:string):Promise<main.Maker>;

export function GetModel(arg1:string):Promise<main.Model>;

export function GetVehicle(arg1:string):Promise<main.Vehicle>;

export function UpdateMaker(arg1:main.Maker):Promise<void>;

export function UpdateModel(arg1:main.Model):Promise<void>;

export function UpdateVehicle(arg1:main.Vehicle):Promise<void>;
